// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/listing/listing.proto

/*
Package listing is a generated protocol buffer package.

It is generated from these files:
	proto/listing/listing.proto

It has these top-level messages:
	Listing
	GetListingRequest
	GetListingResponse
	GetListingsRequest
	GetListingsResponse
	PostListingRequest
	PostListingResponse
	UpdateListingRequest
	UpdateListingResponse
	DeleteListingRequest
	DeleteListingResponse
*/
package listing

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Listing struct {
	Id          string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CreatedAt   int64   `protobuf:"varint,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt   int64   `protobuf:"varint,3,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	Name        string  `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Description string  `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Cost        float32 `protobuf:"fixed32,6,opt,name=cost" json:"cost,omitempty"`
}

func (m *Listing) Reset()                    { *m = Listing{} }
func (m *Listing) String() string            { return proto.CompactTextString(m) }
func (*Listing) ProtoMessage()               {}
func (*Listing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Listing) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Listing) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Listing) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Listing) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Listing) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Listing) GetCost() float32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

type GetListingRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetListingRequest) Reset()                    { *m = GetListingRequest{} }
func (m *GetListingRequest) String() string            { return proto.CompactTextString(m) }
func (*GetListingRequest) ProtoMessage()               {}
func (*GetListingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetListingRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetListingResponse struct {
	Data *Listing `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *GetListingResponse) Reset()                    { *m = GetListingResponse{} }
func (m *GetListingResponse) String() string            { return proto.CompactTextString(m) }
func (*GetListingResponse) ProtoMessage()               {}
func (*GetListingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetListingResponse) GetData() *Listing {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetListingsRequest struct {
}

func (m *GetListingsRequest) Reset()                    { *m = GetListingsRequest{} }
func (m *GetListingsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetListingsRequest) ProtoMessage()               {}
func (*GetListingsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type GetListingsResponse struct {
	Data []*Listing `protobuf:"bytes,8,rep,name=data" json:"data,omitempty"`
}

func (m *GetListingsResponse) Reset()                    { *m = GetListingsResponse{} }
func (m *GetListingsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetListingsResponse) ProtoMessage()               {}
func (*GetListingsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetListingsResponse) GetData() []*Listing {
	if m != nil {
		return m.Data
	}
	return nil
}

type PostListingRequest struct {
	CreatedAt   int64   `protobuf:"varint,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt   int64   `protobuf:"varint,3,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	Name        string  `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Description string  `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Cost        float32 `protobuf:"fixed32,6,opt,name=cost" json:"cost,omitempty"`
}

func (m *PostListingRequest) Reset()                    { *m = PostListingRequest{} }
func (m *PostListingRequest) String() string            { return proto.CompactTextString(m) }
func (*PostListingRequest) ProtoMessage()               {}
func (*PostListingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PostListingRequest) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *PostListingRequest) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *PostListingRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PostListingRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PostListingRequest) GetCost() float32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

type PostListingResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *PostListingResponse) Reset()                    { *m = PostListingResponse{} }
func (m *PostListingResponse) String() string            { return proto.CompactTextString(m) }
func (*PostListingResponse) ProtoMessage()               {}
func (*PostListingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PostListingResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateListingRequest struct {
	Id          string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name        string  `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Description string  `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Cost        float32 `protobuf:"fixed32,6,opt,name=cost" json:"cost,omitempty"`
}

func (m *UpdateListingRequest) Reset()                    { *m = UpdateListingRequest{} }
func (m *UpdateListingRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateListingRequest) ProtoMessage()               {}
func (*UpdateListingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UpdateListingRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateListingRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateListingRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateListingRequest) GetCost() float32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

type UpdateListingResponse struct {
	Msg string `protobuf:"bytes,7,opt,name=msg" json:"msg,omitempty"`
}

func (m *UpdateListingResponse) Reset()                    { *m = UpdateListingResponse{} }
func (m *UpdateListingResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateListingResponse) ProtoMessage()               {}
func (*UpdateListingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateListingResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DeleteListingRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteListingRequest) Reset()                    { *m = DeleteListingRequest{} }
func (m *DeleteListingRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteListingRequest) ProtoMessage()               {}
func (*DeleteListingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DeleteListingRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteListingResponse struct {
	Msg string `protobuf:"bytes,7,opt,name=msg" json:"msg,omitempty"`
}

func (m *DeleteListingResponse) Reset()                    { *m = DeleteListingResponse{} }
func (m *DeleteListingResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteListingResponse) ProtoMessage()               {}
func (*DeleteListingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DeleteListingResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Listing)(nil), "listing.Listing")
	proto.RegisterType((*GetListingRequest)(nil), "listing.GetListingRequest")
	proto.RegisterType((*GetListingResponse)(nil), "listing.GetListingResponse")
	proto.RegisterType((*GetListingsRequest)(nil), "listing.GetListingsRequest")
	proto.RegisterType((*GetListingsResponse)(nil), "listing.GetListingsResponse")
	proto.RegisterType((*PostListingRequest)(nil), "listing.PostListingRequest")
	proto.RegisterType((*PostListingResponse)(nil), "listing.PostListingResponse")
	proto.RegisterType((*UpdateListingRequest)(nil), "listing.UpdateListingRequest")
	proto.RegisterType((*UpdateListingResponse)(nil), "listing.UpdateListingResponse")
	proto.RegisterType((*DeleteListingRequest)(nil), "listing.DeleteListingRequest")
	proto.RegisterType((*DeleteListingResponse)(nil), "listing.DeleteListingResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ListingService service

type ListingServiceClient interface {
	GetListing(ctx context.Context, in *GetListingRequest, opts ...grpc.CallOption) (*GetListingResponse, error)
	GetListings(ctx context.Context, in *GetListingsRequest, opts ...grpc.CallOption) (*GetListingsResponse, error)
	PostListing(ctx context.Context, in *PostListingRequest, opts ...grpc.CallOption) (*PostListingResponse, error)
	UpdateListing(ctx context.Context, in *UpdateListingRequest, opts ...grpc.CallOption) (*UpdateListingResponse, error)
	DeleteListing(ctx context.Context, in *DeleteListingRequest, opts ...grpc.CallOption) (*DeleteListingResponse, error)
}

type listingServiceClient struct {
	cc *grpc.ClientConn
}

func NewListingServiceClient(cc *grpc.ClientConn) ListingServiceClient {
	return &listingServiceClient{cc}
}

func (c *listingServiceClient) GetListing(ctx context.Context, in *GetListingRequest, opts ...grpc.CallOption) (*GetListingResponse, error) {
	out := new(GetListingResponse)
	err := grpc.Invoke(ctx, "/listing.ListingService/GetListing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingServiceClient) GetListings(ctx context.Context, in *GetListingsRequest, opts ...grpc.CallOption) (*GetListingsResponse, error) {
	out := new(GetListingsResponse)
	err := grpc.Invoke(ctx, "/listing.ListingService/GetListings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingServiceClient) PostListing(ctx context.Context, in *PostListingRequest, opts ...grpc.CallOption) (*PostListingResponse, error) {
	out := new(PostListingResponse)
	err := grpc.Invoke(ctx, "/listing.ListingService/PostListing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingServiceClient) UpdateListing(ctx context.Context, in *UpdateListingRequest, opts ...grpc.CallOption) (*UpdateListingResponse, error) {
	out := new(UpdateListingResponse)
	err := grpc.Invoke(ctx, "/listing.ListingService/UpdateListing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingServiceClient) DeleteListing(ctx context.Context, in *DeleteListingRequest, opts ...grpc.CallOption) (*DeleteListingResponse, error) {
	out := new(DeleteListingResponse)
	err := grpc.Invoke(ctx, "/listing.ListingService/DeleteListing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ListingService service

type ListingServiceServer interface {
	GetListing(context.Context, *GetListingRequest) (*GetListingResponse, error)
	GetListings(context.Context, *GetListingsRequest) (*GetListingsResponse, error)
	PostListing(context.Context, *PostListingRequest) (*PostListingResponse, error)
	UpdateListing(context.Context, *UpdateListingRequest) (*UpdateListingResponse, error)
	DeleteListing(context.Context, *DeleteListingRequest) (*DeleteListingResponse, error)
}

func RegisterListingServiceServer(s *grpc.Server, srv ListingServiceServer) {
	s.RegisterService(&_ListingService_serviceDesc, srv)
}

func _ListingService_GetListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingServiceServer).GetListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/listing.ListingService/GetListing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingServiceServer).GetListing(ctx, req.(*GetListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListingService_GetListings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingServiceServer).GetListings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/listing.ListingService/GetListings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingServiceServer).GetListings(ctx, req.(*GetListingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListingService_PostListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingServiceServer).PostListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/listing.ListingService/PostListing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingServiceServer).PostListing(ctx, req.(*PostListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListingService_UpdateListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingServiceServer).UpdateListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/listing.ListingService/UpdateListing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingServiceServer).UpdateListing(ctx, req.(*UpdateListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListingService_DeleteListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingServiceServer).DeleteListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/listing.ListingService/DeleteListing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingServiceServer).DeleteListing(ctx, req.(*DeleteListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ListingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "listing.ListingService",
	HandlerType: (*ListingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetListing",
			Handler:    _ListingService_GetListing_Handler,
		},
		{
			MethodName: "GetListings",
			Handler:    _ListingService_GetListings_Handler,
		},
		{
			MethodName: "PostListing",
			Handler:    _ListingService_PostListing_Handler,
		},
		{
			MethodName: "UpdateListing",
			Handler:    _ListingService_UpdateListing_Handler,
		},
		{
			MethodName: "DeleteListing",
			Handler:    _ListingService_DeleteListing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/listing/listing.proto",
}

func init() { proto.RegisterFile("proto/listing/listing.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 483 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0x3d, 0x6f, 0x13, 0x41,
	0x10, 0xd5, 0x9d, 0x4d, 0x8c, 0xc7, 0xc4, 0x8a, 0xc7, 0x06, 0x8e, 0x8b, 0x83, 0x4e, 0xcb, 0x87,
	0x4c, 0x8a, 0x9c, 0x30, 0x5d, 0xa8, 0x82, 0x90, 0x68, 0x28, 0x90, 0x11, 0x0d, 0x05, 0xb0, 0xf8,
	0x56, 0xd6, 0x4a, 0x97, 0xdb, 0xe3, 0x76, 0x93, 0x06, 0xd1, 0xf0, 0x03, 0x68, 0x68, 0x69, 0xf8,
	0x4d, 0xfc, 0x05, 0x7e, 0x08, 0xba, 0xbd, 0xdd, 0xb0, 0xf7, 0x11, 0xd3, 0x50, 0xa4, 0xf2, 0x7a,
	0xde, 0xec, 0x7b, 0xcf, 0x33, 0xcf, 0x0b, 0xfb, 0x79, 0x21, 0x94, 0x88, 0x53, 0x2e, 0x15, 0xcf,
	0x36, 0xf6, 0xf3, 0x48, 0x57, 0x71, 0x60, 0xbe, 0x86, 0xf3, 0x8d, 0x10, 0x9b, 0x94, 0xc5, 0x34,
	0xe7, 0x31, 0xcd, 0x32, 0xa1, 0xa8, 0xe2, 0x22, 0x93, 0x55, 0x1b, 0xf9, 0xe9, 0xc1, 0xe0, 0x65,
	0xd5, 0x89, 0x63, 0xf0, 0x79, 0x12, 0x78, 0x91, 0xb7, 0x18, 0xae, 0x7c, 0x9e, 0xe0, 0x01, 0xc0,
	0xba, 0x60, 0x54, 0xb1, 0xe4, 0x3d, 0x55, 0x81, 0x1f, 0x79, 0x8b, 0xde, 0x6a, 0x68, 0x2a, 0x27,
	0xaa, 0x84, 0xcf, 0xf2, 0xc4, 0xc2, 0xbd, 0x0a, 0x36, 0x95, 0x13, 0x85, 0x08, 0xfd, 0x8c, 0x9e,
	0xb2, 0xa0, 0xaf, 0xf9, 0xf4, 0x19, 0x23, 0x18, 0x25, 0x4c, 0xae, 0x0b, 0x9e, 0x97, 0x1e, 0x82,
	0x6b, 0x1a, 0x72, 0x4b, 0xe5, 0xad, 0xb5, 0x90, 0x2a, 0xd8, 0x89, 0xbc, 0x85, 0xbf, 0xd2, 0x67,
	0x72, 0x0f, 0x26, 0x2f, 0x98, 0x32, 0x2e, 0x57, 0xec, 0xd3, 0x19, 0x93, 0xaa, 0x69, 0x96, 0x1c,
	0x03, 0xba, 0x4d, 0x32, 0x17, 0x99, 0x64, 0x78, 0x1f, 0xfa, 0x09, 0x55, 0x54, 0xf7, 0x8d, 0x96,
	0x7b, 0x47, 0x76, 0x46, 0xb6, 0x4f, 0xa3, 0x64, 0xe6, 0xde, 0x95, 0x46, 0x81, 0x3c, 0x85, 0x69,
	0xad, 0xda, 0xa0, 0xbc, 0x1e, 0xf5, 0xb6, 0x50, 0xfe, 0xf0, 0x00, 0x5f, 0x09, 0xd9, 0x74, 0x7d,
	0x55, 0x46, 0xfa, 0x00, 0xa6, 0x35, 0x77, 0xe6, 0xb7, 0x35, 0x87, 0x9a, 0xc3, 0xec, 0x8d, 0x56,
	0xdf, 0x3e, 0xfc, 0xff, 0x68, 0xec, 0x11, 0xdc, 0x6c, 0x28, 0x1a, 0x6b, 0x7b, 0xd0, 0x3b, 0x95,
	0x9b, 0x60, 0xa0, 0x69, 0xca, 0x23, 0x79, 0x08, 0xb3, 0xe7, 0x2c, 0x65, 0xff, 0x32, 0x57, 0x52,
	0x36, 0xfa, 0x2e, 0xa3, 0x5c, 0x7e, 0xeb, 0xc3, 0xd8, 0x74, 0xbd, 0x66, 0xc5, 0x39, 0x5f, 0x33,
	0xfc, 0x00, 0xf0, 0x37, 0x05, 0x18, 0x5e, 0xac, 0xbb, 0x95, 0xc8, 0x70, 0xbf, 0x13, 0xab, 0xb4,
	0xc8, 0x9d, 0xaf, 0xbf, 0x7e, 0x7f, 0xf7, 0xa7, 0x38, 0x89, 0xcf, 0x1f, 0xdb, 0x7f, 0xaa, 0x8c,
	0x3f, 0xf3, 0xe4, 0x0b, 0xbe, 0x83, 0x91, 0x93, 0x33, 0xec, 0xa2, 0xb1, 0x99, 0x0c, 0xe7, 0xdd,
	0xa0, 0x11, 0x99, 0x69, 0x91, 0x31, 0xde, 0x70, 0x45, 0x90, 0xc2, 0xc8, 0xd9, 0xb5, 0xc3, 0xdf,
	0xce, 0xa7, 0xc3, 0xdf, 0x11, 0x0f, 0x72, 0x5b, 0xf3, 0x4f, 0x48, 0x8d, 0xff, 0xd8, 0x3b, 0xc4,
	0x14, 0x76, 0x6b, 0x5b, 0xc3, 0x83, 0x0b, 0x9e, 0xae, 0xfc, 0x84, 0x77, 0x2f, 0x83, 0x8d, 0xd0,
	0x5c, 0x0b, 0xdd, 0x5a, 0xb6, 0xa7, 0x55, 0xaa, 0x71, 0xd8, 0xad, 0x2d, 0xd4, 0x51, 0xeb, 0x0a,
	0x84, 0xa3, 0xd6, 0x99, 0x03, 0xbb, 0x9b, 0xc3, 0xb6, 0xda, 0xb3, 0xe1, 0x5b, 0xfb, 0x8e, 0x7e,
	0xdc, 0xd1, 0x0f, 0xe6, 0x93, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5e, 0xee, 0x94, 0xad, 0x76,
	0x05, 0x00, 0x00,
}
