// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/listing/listing.proto

/*
Package listing is a generated protocol buffer package.

It is generated from these files:
	proto/listing/listing.proto

It has these top-level messages:
	Address
	Listing
	GetListingRequest
	GetListingResponse
	GetListingsRequest
	GetListingsResponse
	PostListingRequest
	PostListingResponse
	UpdateListingRequest
	UpdateListingResponse
	DeleteListingRequest
	DeleteListingResponse
*/
package listing

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// @inject_tag: bson:"_id,omitempty"
type Address struct {
	Lat float32 `protobuf:"fixed32,1,opt,name=lat" json:"lat,omitempty"`
	Lng float32 `protobuf:"fixed32,2,opt,name=lng" json:"lng,omitempty"`
	// @inject_tag: bson:"address_1,omitempty"
	Address_1 string `protobuf:"bytes,3,opt,name=address_1,json=address1" json:"address_1,omitempty" bson:"address_1,omitempty"`
	// @inject_tag: bson:"address_2,omitempty"
	Address_2 string `protobuf:"bytes,4,opt,name=address_2,json=address2" json:"address_2,omitempty" bson:"address_2,omitempty"`
	// @inject_tag: bson:"postal_code,omitempty"
	PostalCode string `protobuf:"bytes,5,opt,name=postal_code,json=postalCode" json:"postal_code,omitempty" bson:"postal_code,omitempty"`
	Country    string `protobuf:"bytes,6,opt,name=country" json:"country,omitempty"`
	City       string `protobuf:"bytes,7,opt,name=city" json:"city,omitempty"`
	State      string `protobuf:"bytes,8,opt,name=state" json:"state,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Address) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Address) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *Address) GetAddress_1() string {
	if m != nil {
		return m.Address_1
	}
	return ""
}

func (m *Address) GetAddress_2() string {
	if m != nil {
		return m.Address_2
	}
	return ""
}

func (m *Address) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

// We need to inject the tags to ensure the naming in the database is correct
type Listing struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// @inject_tag: bson:"created_at,omitempty"
	CreatedAt int64 `protobuf:"varint,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty" bson:"created_at,omitempty"`
	// @inject_tag: bson:"modified_at,omitempty"
	ModifiedAt  int64   `protobuf:"varint,3,opt,name=modified_at,json=modifiedAt" json:"modified_at,omitempty" bson:"modified_at,omitempty"`
	Title       string  `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
	Cost        float32 `protobuf:"fixed32,5,opt,name=cost" json:"cost,omitempty"`
	Description string  `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	// @inject_tag: bson:"cover_photo,omitempty"
	CoverPhoto string   `protobuf:"bytes,7,opt,name=cover_photo,json=coverPhoto" json:"cover_photo,omitempty" bson:"cover_photo,omitempty"`
	Address    *Address `protobuf:"bytes,8,opt,name=address" json:"address,omitempty"`
	// @inject_tag: bson:"is_published,omitempty"
	IsPublished bool `protobuf:"varint,9,opt,name=is_published,json=isPublished" json:"is_published,omitempty" bson:"is_published,omitempty"`
	// @inject_tag: bson:"is_available,omitempty"
	IsAvailable bool `protobuf:"varint,10,opt,name=is_available,json=isAvailable" json:"is_available,omitempty" bson:"is_available,omitempty"`
}

func (m *Listing) Reset()                    { *m = Listing{} }
func (m *Listing) String() string            { return proto.CompactTextString(m) }
func (*Listing) ProtoMessage()               {}
func (*Listing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Listing) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Listing) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Listing) GetModifiedAt() int64 {
	if m != nil {
		return m.ModifiedAt
	}
	return 0
}

func (m *Listing) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Listing) GetCost() float32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *Listing) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Listing) GetCoverPhoto() string {
	if m != nil {
		return m.CoverPhoto
	}
	return ""
}

func (m *Listing) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Listing) GetIsPublished() bool {
	if m != nil {
		return m.IsPublished
	}
	return false
}

func (m *Listing) GetIsAvailable() bool {
	if m != nil {
		return m.IsAvailable
	}
	return false
}

type GetListingRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetListingRequest) Reset()                    { *m = GetListingRequest{} }
func (m *GetListingRequest) String() string            { return proto.CompactTextString(m) }
func (*GetListingRequest) ProtoMessage()               {}
func (*GetListingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetListingRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetListingResponse struct {
	Data *Listing `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *GetListingResponse) Reset()                    { *m = GetListingResponse{} }
func (m *GetListingResponse) String() string            { return proto.CompactTextString(m) }
func (*GetListingResponse) ProtoMessage()               {}
func (*GetListingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetListingResponse) GetData() *Listing {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetListingsRequest struct {
}

func (m *GetListingsRequest) Reset()                    { *m = GetListingsRequest{} }
func (m *GetListingsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetListingsRequest) ProtoMessage()               {}
func (*GetListingsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type GetListingsResponse struct {
	Data []*Listing `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *GetListingsResponse) Reset()                    { *m = GetListingsResponse{} }
func (m *GetListingsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetListingsResponse) ProtoMessage()               {}
func (*GetListingsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetListingsResponse) GetData() []*Listing {
	if m != nil {
		return m.Data
	}
	return nil
}

type PostListingRequest struct {
	// string id = 1;
	// @inject_tag: bson:"created_at,omitempty"
	CreatedAt int64 `protobuf:"varint,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty" bson:"created_at,omitempty"`
	// @inject_tag: bson:"modified_at,omitempty"
	ModifiedAt  int64   `protobuf:"varint,3,opt,name=modified_at,json=modifiedAt" json:"modified_at,omitempty" bson:"modified_at,omitempty"`
	Title       string  `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
	Cost        float32 `protobuf:"fixed32,5,opt,name=cost" json:"cost,omitempty"`
	Description string  `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	// @inject_tag: bson:"cover_photo,omitempty"
	CoverPhoto string   `protobuf:"bytes,7,opt,name=cover_photo,json=coverPhoto" json:"cover_photo,omitempty" bson:"cover_photo,omitempty"`
	Address    *Address `protobuf:"bytes,8,opt,name=address" json:"address,omitempty"`
	// @inject_tag: bson:"is_published,omitempty"
	IsPublished bool `protobuf:"varint,9,opt,name=is_published,json=isPublished" json:"is_published,omitempty" bson:"is_published,omitempty"`
	// @inject_tag: bson:"is_available,omitempty"
	IsAvailable bool `protobuf:"varint,10,opt,name=is_available,json=isAvailable" json:"is_available,omitempty" bson:"is_available,omitempty"`
}

func (m *PostListingRequest) Reset()                    { *m = PostListingRequest{} }
func (m *PostListingRequest) String() string            { return proto.CompactTextString(m) }
func (*PostListingRequest) ProtoMessage()               {}
func (*PostListingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PostListingRequest) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *PostListingRequest) GetModifiedAt() int64 {
	if m != nil {
		return m.ModifiedAt
	}
	return 0
}

func (m *PostListingRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PostListingRequest) GetCost() float32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *PostListingRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PostListingRequest) GetCoverPhoto() string {
	if m != nil {
		return m.CoverPhoto
	}
	return ""
}

func (m *PostListingRequest) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *PostListingRequest) GetIsPublished() bool {
	if m != nil {
		return m.IsPublished
	}
	return false
}

func (m *PostListingRequest) GetIsAvailable() bool {
	if m != nil {
		return m.IsAvailable
	}
	return false
}

type PostListingResponse struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *PostListingResponse) Reset()                    { *m = PostListingResponse{} }
func (m *PostListingResponse) String() string            { return proto.CompactTextString(m) }
func (*PostListingResponse) ProtoMessage()               {}
func (*PostListingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PostListingResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type UpdateListingRequest struct {
	Id          string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CreatedAt   int64    `protobuf:"varint,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	ModifiedAt  int64    `protobuf:"varint,3,opt,name=modified_at,json=modifiedAt" json:"modified_at,omitempty"`
	Title       string   `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
	Cost        float32  `protobuf:"fixed32,5,opt,name=cost" json:"cost,omitempty"`
	Description string   `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	CoverPhoto  string   `protobuf:"bytes,7,opt,name=cover_photo,json=coverPhoto" json:"cover_photo,omitempty"`
	Address     *Address `protobuf:"bytes,8,opt,name=address" json:"address,omitempty"`
	IsPublished bool     `protobuf:"varint,9,opt,name=is_published,json=isPublished" json:"is_published,omitempty"`
	IsAvailable bool     `protobuf:"varint,10,opt,name=is_available,json=isAvailable" json:"is_available,omitempty"`
}

func (m *UpdateListingRequest) Reset()                    { *m = UpdateListingRequest{} }
func (m *UpdateListingRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateListingRequest) ProtoMessage()               {}
func (*UpdateListingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateListingRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateListingRequest) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *UpdateListingRequest) GetModifiedAt() int64 {
	if m != nil {
		return m.ModifiedAt
	}
	return 0
}

func (m *UpdateListingRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateListingRequest) GetCost() float32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *UpdateListingRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateListingRequest) GetCoverPhoto() string {
	if m != nil {
		return m.CoverPhoto
	}
	return ""
}

func (m *UpdateListingRequest) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *UpdateListingRequest) GetIsPublished() bool {
	if m != nil {
		return m.IsPublished
	}
	return false
}

func (m *UpdateListingRequest) GetIsAvailable() bool {
	if m != nil {
		return m.IsAvailable
	}
	return false
}

type UpdateListingResponse struct {
	Msg string `protobuf:"bytes,11,opt,name=msg" json:"msg,omitempty"`
}

func (m *UpdateListingResponse) Reset()                    { *m = UpdateListingResponse{} }
func (m *UpdateListingResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateListingResponse) ProtoMessage()               {}
func (*UpdateListingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UpdateListingResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DeleteListingRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteListingRequest) Reset()                    { *m = DeleteListingRequest{} }
func (m *DeleteListingRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteListingRequest) ProtoMessage()               {}
func (*DeleteListingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DeleteListingRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteListingResponse struct {
	Msg string `protobuf:"bytes,11,opt,name=msg" json:"msg,omitempty"`
}

func (m *DeleteListingResponse) Reset()                    { *m = DeleteListingResponse{} }
func (m *DeleteListingResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteListingResponse) ProtoMessage()               {}
func (*DeleteListingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *DeleteListingResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Address)(nil), "listing.Address")
	proto.RegisterType((*Listing)(nil), "listing.Listing")
	proto.RegisterType((*GetListingRequest)(nil), "listing.GetListingRequest")
	proto.RegisterType((*GetListingResponse)(nil), "listing.GetListingResponse")
	proto.RegisterType((*GetListingsRequest)(nil), "listing.GetListingsRequest")
	proto.RegisterType((*GetListingsResponse)(nil), "listing.GetListingsResponse")
	proto.RegisterType((*PostListingRequest)(nil), "listing.PostListingRequest")
	proto.RegisterType((*PostListingResponse)(nil), "listing.PostListingResponse")
	proto.RegisterType((*UpdateListingRequest)(nil), "listing.UpdateListingRequest")
	proto.RegisterType((*UpdateListingResponse)(nil), "listing.UpdateListingResponse")
	proto.RegisterType((*DeleteListingRequest)(nil), "listing.DeleteListingRequest")
	proto.RegisterType((*DeleteListingResponse)(nil), "listing.DeleteListingResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ListingService service

type ListingServiceClient interface {
	GetListing(ctx context.Context, in *GetListingRequest, opts ...grpc.CallOption) (*GetListingResponse, error)
	GetListings(ctx context.Context, in *GetListingsRequest, opts ...grpc.CallOption) (*GetListingsResponse, error)
	PostListing(ctx context.Context, in *PostListingRequest, opts ...grpc.CallOption) (*PostListingResponse, error)
	UpdateListing(ctx context.Context, in *UpdateListingRequest, opts ...grpc.CallOption) (*UpdateListingResponse, error)
	DeleteListing(ctx context.Context, in *DeleteListingRequest, opts ...grpc.CallOption) (*DeleteListingResponse, error)
}

type listingServiceClient struct {
	cc *grpc.ClientConn
}

func NewListingServiceClient(cc *grpc.ClientConn) ListingServiceClient {
	return &listingServiceClient{cc}
}

func (c *listingServiceClient) GetListing(ctx context.Context, in *GetListingRequest, opts ...grpc.CallOption) (*GetListingResponse, error) {
	out := new(GetListingResponse)
	err := grpc.Invoke(ctx, "/listing.ListingService/GetListing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingServiceClient) GetListings(ctx context.Context, in *GetListingsRequest, opts ...grpc.CallOption) (*GetListingsResponse, error) {
	out := new(GetListingsResponse)
	err := grpc.Invoke(ctx, "/listing.ListingService/GetListings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingServiceClient) PostListing(ctx context.Context, in *PostListingRequest, opts ...grpc.CallOption) (*PostListingResponse, error) {
	out := new(PostListingResponse)
	err := grpc.Invoke(ctx, "/listing.ListingService/PostListing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingServiceClient) UpdateListing(ctx context.Context, in *UpdateListingRequest, opts ...grpc.CallOption) (*UpdateListingResponse, error) {
	out := new(UpdateListingResponse)
	err := grpc.Invoke(ctx, "/listing.ListingService/UpdateListing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingServiceClient) DeleteListing(ctx context.Context, in *DeleteListingRequest, opts ...grpc.CallOption) (*DeleteListingResponse, error) {
	out := new(DeleteListingResponse)
	err := grpc.Invoke(ctx, "/listing.ListingService/DeleteListing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ListingService service

type ListingServiceServer interface {
	GetListing(context.Context, *GetListingRequest) (*GetListingResponse, error)
	GetListings(context.Context, *GetListingsRequest) (*GetListingsResponse, error)
	PostListing(context.Context, *PostListingRequest) (*PostListingResponse, error)
	UpdateListing(context.Context, *UpdateListingRequest) (*UpdateListingResponse, error)
	DeleteListing(context.Context, *DeleteListingRequest) (*DeleteListingResponse, error)
}

func RegisterListingServiceServer(s *grpc.Server, srv ListingServiceServer) {
	s.RegisterService(&_ListingService_serviceDesc, srv)
}

func _ListingService_GetListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingServiceServer).GetListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/listing.ListingService/GetListing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingServiceServer).GetListing(ctx, req.(*GetListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListingService_GetListings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingServiceServer).GetListings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/listing.ListingService/GetListings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingServiceServer).GetListings(ctx, req.(*GetListingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListingService_PostListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingServiceServer).PostListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/listing.ListingService/PostListing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingServiceServer).PostListing(ctx, req.(*PostListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListingService_UpdateListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingServiceServer).UpdateListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/listing.ListingService/UpdateListing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingServiceServer).UpdateListing(ctx, req.(*UpdateListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListingService_DeleteListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingServiceServer).DeleteListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/listing.ListingService/DeleteListing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingServiceServer).DeleteListing(ctx, req.(*DeleteListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ListingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "listing.ListingService",
	HandlerType: (*ListingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetListing",
			Handler:    _ListingService_GetListing_Handler,
		},
		{
			MethodName: "GetListings",
			Handler:    _ListingService_GetListings_Handler,
		},
		{
			MethodName: "PostListing",
			Handler:    _ListingService_PostListing_Handler,
		},
		{
			MethodName: "UpdateListing",
			Handler:    _ListingService_UpdateListing_Handler,
		},
		{
			MethodName: "DeleteListing",
			Handler:    _ListingService_DeleteListing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/listing/listing.proto",
}

func init() { proto.RegisterFile("proto/listing/listing.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 661 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x56, 0xc1, 0x72, 0xd3, 0x3c,
	0x10, 0x9e, 0x38, 0x69, 0xd3, 0xac, 0xdb, 0x4e, 0xbb, 0xcd, 0xff, 0x63, 0xd2, 0x16, 0x82, 0x61,
	0xa0, 0xf4, 0xd0, 0x4c, 0xc3, 0xad, 0x9c, 0x02, 0xcc, 0x70, 0xe1, 0xd0, 0x31, 0xc3, 0x85, 0x03,
	0x41, 0xb5, 0x44, 0xaa, 0x19, 0xd7, 0x32, 0x96, 0x9a, 0x99, 0x0e, 0xc3, 0x85, 0x07, 0xe0, 0xc2,
	0xa3, 0x70, 0xe1, 0x05, 0xb8, 0x71, 0xe3, 0x15, 0x78, 0x10, 0xc6, 0xb2, 0xd4, 0xca, 0x89, 0x1b,
	0x5e, 0xa0, 0xa7, 0x4a, 0xdf, 0x6e, 0xbf, 0x4f, 0xfb, 0xed, 0x4a, 0x31, 0x6c, 0x67, 0xb9, 0x50,
	0x62, 0x90, 0x70, 0xa9, 0x78, 0x3a, 0xb1, 0x7f, 0x0f, 0x34, 0x8a, 0x6d, 0xb3, 0xed, 0xed, 0x4c,
	0x84, 0x98, 0x24, 0x6c, 0x40, 0x32, 0x3e, 0x20, 0x69, 0x2a, 0x14, 0x51, 0x5c, 0xa4, 0xb2, 0x4c,
	0x0b, 0x7f, 0x35, 0xa0, 0x3d, 0xa2, 0x34, 0x67, 0x52, 0xe2, 0x06, 0x34, 0x13, 0xa2, 0x82, 0x46,
	0xbf, 0xb1, 0xe7, 0x45, 0xc5, 0x52, 0x23, 0xe9, 0x24, 0xf0, 0x0c, 0x92, 0x4e, 0x70, 0x1b, 0x3a,
	0xa4, 0x4c, 0x1f, 0x1f, 0x06, 0xcd, 0x7e, 0x63, 0xaf, 0x13, 0xad, 0x18, 0xe0, 0xd0, 0x0d, 0x0e,
	0x83, 0x56, 0x25, 0x38, 0xc4, 0xbb, 0xe0, 0x67, 0x42, 0x2a, 0x92, 0x8c, 0x63, 0x41, 0x59, 0xb0,
	0xa4, 0xc3, 0x50, 0x42, 0xcf, 0x05, 0x65, 0x18, 0x40, 0x3b, 0x16, 0xe7, 0xa9, 0xca, 0x2f, 0x82,
	0x65, 0x1d, 0xb4, 0x5b, 0x44, 0x68, 0xc5, 0x5c, 0x5d, 0x04, 0x6d, 0x0d, 0xeb, 0x35, 0x76, 0x61,
	0x49, 0x2a, 0xa2, 0x58, 0xb0, 0xa2, 0xc1, 0x72, 0x13, 0xfe, 0xf0, 0xa0, 0xfd, 0xaa, 0x2c, 0x1c,
	0xd7, 0xc1, 0xe3, 0x54, 0x57, 0xd3, 0x89, 0x3c, 0x4e, 0x71, 0x17, 0x20, 0xce, 0x19, 0x51, 0x8c,
	0x8e, 0x89, 0xd2, 0x35, 0x35, 0xa3, 0x8e, 0x41, 0x46, 0xaa, 0x38, 0xdf, 0x99, 0xa0, 0xfc, 0x03,
	0x2f, 0xe3, 0x4d, 0x1d, 0x07, 0x0b, 0x8d, 0x54, 0xa1, 0xa8, 0xb8, 0x4a, 0x98, 0xa9, 0xac, 0xdc,
	0xe8, 0xb3, 0x09, 0xa9, 0x74, 0x3d, 0x5e, 0xa4, 0xd7, 0xd8, 0x07, 0x9f, 0x32, 0x19, 0xe7, 0x3c,
	0x2b, 0xac, 0x36, 0xd5, 0xb8, 0x50, 0x21, 0x16, 0x8b, 0x29, 0xcb, 0xc7, 0xd9, 0xa9, 0x50, 0xc2,
	0x14, 0x06, 0x1a, 0x3a, 0x2e, 0x10, 0xdc, 0x87, 0xb6, 0x71, 0x4e, 0x17, 0xe8, 0x0f, 0x37, 0x0e,
	0x6c, 0x7f, 0x4d, 0xbb, 0x22, 0x9b, 0x80, 0xf7, 0x60, 0x95, 0xcb, 0x71, 0x76, 0x7e, 0x92, 0x70,
	0x79, 0xca, 0x68, 0xd0, 0xe9, 0x37, 0xf6, 0x56, 0x22, 0x9f, 0xcb, 0x63, 0x0b, 0x99, 0x14, 0x32,
	0x25, 0x3c, 0x21, 0x27, 0x09, 0x0b, 0xc0, 0xa6, 0x8c, 0x2c, 0x14, 0xde, 0x87, 0xcd, 0x97, 0x4c,
	0x19, 0xf3, 0x22, 0xf6, 0xf1, 0x9c, 0x49, 0x35, 0xeb, 0x61, 0x78, 0x04, 0xe8, 0x26, 0xc9, 0x4c,
	0xa4, 0x92, 0xe1, 0x03, 0x68, 0x51, 0xa2, 0x88, 0xce, 0x73, 0x4f, 0x6a, 0xf3, 0x74, 0x34, 0xec,
	0xba, 0xff, 0x2b, 0x8d, 0x42, 0xf8, 0x14, 0xb6, 0x2a, 0xe8, 0x1c, 0x65, 0x73, 0x01, 0xe5, 0x77,
	0x0f, 0xf0, 0x58, 0xc8, 0xd9, 0x53, 0xdf, 0x74, 0x7a, 0x61, 0xa7, 0x1f, 0xc1, 0x56, 0xc5, 0x34,
	0x63, 0xf9, 0x06, 0x34, 0xcf, 0xe4, 0xc4, 0x34, 0xbb, 0x58, 0x86, 0x3f, 0x3d, 0xe8, 0xbe, 0xc9,
	0x28, 0x51, 0x6c, 0xf1, 0x58, 0xdc, 0x18, 0xbe, 0xd8, 0xf0, 0xc7, 0xf0, 0xdf, 0x8c, 0x8d, 0x55,
	0xcb, 0xfd, 0x2b, 0xcb, 0x1f, 0x42, 0xf7, 0x05, 0x4b, 0xd8, 0xbf, 0x1c, 0x2f, 0x28, 0x67, 0xf2,
	0xae, 0xa3, 0x1c, 0x7e, 0x6d, 0xc1, 0xba, 0xc9, 0x7a, 0xcd, 0xf2, 0x29, 0x8f, 0x19, 0xbe, 0x07,
	0xb8, 0xba, 0x74, 0xd8, 0xbb, 0xac, 0x7f, 0xee, 0x01, 0xe8, 0x6d, 0xd7, 0xc6, 0x4a, 0xad, 0xf0,
	0xf6, 0x97, 0xdf, 0x7f, 0xbe, 0x79, 0x5b, 0xb8, 0x39, 0x98, 0x1e, 0xda, 0x9f, 0x1f, 0x39, 0xf8,
	0xc4, 0xe9, 0x67, 0x7c, 0x07, 0xbe, 0x73, 0xad, 0xb1, 0x8e, 0xc6, 0x3e, 0x01, 0xbd, 0x9d, 0xfa,
	0xa0, 0x11, 0xe9, 0x6a, 0x91, 0x75, 0x5c, 0x75, 0x45, 0x90, 0x80, 0xef, 0xcc, 0xb0, 0xc3, 0x3f,
	0xff, 0x1c, 0x38, 0xfc, 0x35, 0x63, 0x1f, 0xde, 0xd2, 0xfc, 0x9b, 0x61, 0x85, 0xff, 0xa8, 0xb1,
	0x8f, 0x09, 0xac, 0x55, 0xba, 0x86, 0xbb, 0x97, 0x3c, 0x75, 0x97, 0xa2, 0x77, 0xe7, 0xba, 0xb0,
	0x11, 0xda, 0xd1, 0x42, 0xff, 0x0f, 0xe7, 0xdd, 0x2a, 0xd4, 0x38, 0xac, 0x55, 0x1a, 0xea, 0xa8,
	0xd5, 0x0d, 0x84, 0xa3, 0x56, 0x3b, 0x07, 0xb6, 0x37, 0xfb, 0xf3, 0x6a, 0xcf, 0x3a, 0x6f, 0xed,
	0xc7, 0xc1, 0xc9, 0xb2, 0xfe, 0x0a, 0x78, 0xf2, 0x37, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x8c, 0x41,
	0xc5, 0x4b, 0x08, 0x00, 0x00,
}
